#!/bin/sh -e

PREREQS=""

# Output pre-requisites

prereqs()
{
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
    ;;
esac

. /scripts/functions

MNT=/host
ROOT_MNT=${rootmnt}${MNT}

_log_msg "Moving LVM loops host device mount point from \"${MNT}\" to \"${ROOT_MNT}\"...\n"

mount -o remount,rw ${rootmnt} || panic "Cannot remount \"${rootmnt}\" R/W."

[ -d ${ROOT_MNT} ] || (mkdir -p ${ROOT_MNT} && chmod 755 ${ROOT_MNT}) || panic "Cannot create \"${ROOT_MNT}\" mount point."

mount -n -o move ${MNT} ${ROOT_MNT} || panic "Cannot move \"${MNT}\" to \"${ROOT_MNT}\"."

log_end_msg "Done"
