#!/bin/bash

if [ $# -lt 1 ]; then
  echo "$(basename $0) [Compressed boot image file basename]"
  exit 1
fi

if [[ $EUID > 0 ]]; then # we can compare directly with this syntax.
  echo "Please run as root/sudo!"
  exit 1
fi

tar -czvf $1.tar.gz /boot