#!/bin/bash

if [ $# -lt 3 ]; then
  echo "$(basename $0) [Boot device] [Boot partition mount point] [Boot image compressed file name]"
  exit 1
fi

if [[ $EUID > 0 ]]; then # we can compare directly with this syntax.
  echo "Please run as root/sudo!"
  exit 1
fi

DEV=$1
MNT=$2
BAK=$3

[ -b ${DEV} ] || { 
  echo "Invalid device \"${DEV}\"." >&2
  exit 1
}

mountpoint ${MNT} &>/dev/null || { 
  echo "Invalid mount point \"${MNT}\"." >&2
  exit 1 
}

[ -f ${BAK} ] || {
  echo "Invalid backup file \"${BAK}\"." >&2
  exit 1 
}

command -v parted > /dev/null || apt install -y parted || exit $?

echo -e "Target device info:\n"
parted ${DEV} print

echo -e "Target mount point info:\n"
ls ${MNT}

echo ""
read -p "Are you sure? (CTRL-C to exit)"

   grub-install --force --boot-directory=${MNT} ${DEV} \
&& cd ${MNT} \
&& rm -rf ${MNT}/* \
&& tar xvf ${BAK} --strip-components=1 -C ${MNT}

