#!/bin/sh

. /usr/share/grub/grub-mkconfig_lib
. /etc/default/grub.d/buddy-linux.cfg

# Get kernels list

KERNELS=$(for file in /boot/vmlinuz-* /vmlinuz-* /boot/kernel-* ; do
  if grub_file_is_not_garbage "${file}" ; then echo -n "${file} " ; fi
done)

# Set default

latest_kernel=$(version_find_latest ${KERNELS} | sed -e "s,^[^0-9]*-,,g")

if [ ${WANT_PARAGON_NTFS_EXPRESS_DRIVER} = 0 ]; then

cat << EOF
set default="Loopback (${latest_kernel} - \"${HOST_DEV_FSTYPE}\")"
EOF

  echo "Default loopback kernel will be \"${latest_kernel}\"." 1>&2
fi

# Adding entries

for kernel in ${KERNELS}; do

  KERNEL=$(basename $kernel | sed -e "s,^[^0-9]*-,,g")
  echo "Found loopback kernel \"${KERNEL}\" - \"${HOST_DEV_FSTYPE}\"." 1>&2

cat << EOF

menuentry 'Loopback (${KERNEL} - \"${HOST_DEV_FSTYPE}\")' --class gnu-linux --class gnu --class os {
  echo "Loading modules..."

  insmod xzio
  insmod part_msdos

  echo "Loading kernel \"${KERNEL}\"..."

  set root=${BOOT_PART}

  linux  /vmlinuz-${KERNEL} root=${ROOT_DEV} lvm_loops_host_dev=${HOST_DEV} lvm_loops_host_fstype=${HOST_DEV_FSTYPE} lvm_loops_host_fsoptions=${HOST_DEV_FSOPTIONS} lvm_loops_mask=${LVM_LOOPS_MASK} max_loop=${MAX_LOOPS} ${KERNEL_DEFAULTS}

  echo "Booting..."
  initrd /initrd.img-${KERNEL}
}
EOF

done

# Loopback recovery

if [ ${WANT_RECOVERY} = 1 ] && [ ${WANT_PARAGON_NTFS_EXPRESS_DRIVER} = 0 ]; then

echo "Adding loopback recovery kernel \"${latest_kernel}\"." 1>&2

cat << EOF

menuentry 'Loopback (Recovery - \"${HOST_DEV_FSTYPE}\")' --class gnu-linux --class gnu --class os {
  echo "Loading modules..."

  insmod xzio
  insmod part_msdos

  echo "Loading kernel \"${latest_kernel}\"..."

  set root=${BOOT_PART}

  linux  /vmlinuz-${latest_kernel} root=${ROOT_DEV} lvm_loops_host_dev=${HOST_DEV} lvm_loops_host_fstype=${HOST_DEV_FSTYPE} lvm_loops_host_fsoptions=${HOST_DEV_FSOPTIONS} lvm_loops_mask=${LVM_LOOPS_MASK} max_loop=${MAX_LOOPS} ${KERNEL_DEFAULTS} recovery nomodeset

  echo "Booting recovery..."
  initrd /initrd.img-${KERNEL}
}
EOF

fi

# Net console

if [ ! -z "${NET_CONSOLE}" ] && [ ${WANT_PARAGON_NTFS_EXPRESS_DRIVER} = 0 ]; then

echo "Adding loopback net console kernel \"${latest_kernel}\"." 1>&2

cat << EOF

menuentry 'Loopback (NetConsole - \"${HOST_DEV_FSTYPE}\")' --class gnu-linux --class gnu --class os {
  echo "Loading modules..."

  insmod xzio
  insmod part_msdos

  echo "Loading kernel \"${latest_kernel}\"..."

  set root=${BOOT_PART}

  linux  /vmlinuz-${latest_kernel} root=${ROOT_DEV} lvm_loops_host_dev=${HOST_DEV} lvm_loops_host_fstype=${HOST_DEV_FSTYPE} lvm_loops_host_fsoptions=${HOST_DEV_FSOPTIONS} lvm_loops_mask=${LVM_LOOPS_MASK} max_loop=${MAX_LOOPS} ${KERNEL_DEFAULTS} ${NET_CONSOLE}

  echo "Booting with net console..."
  initrd /initrd.img-${latest_kernel}
}
EOF

fi
