#!/bin/bash

. /etc/default/grub
. /etc/default/grub.d/buddy-linux.cfg
. /usr/share/grub/grub-mkconfig_lib

function addMenuEntry {
  local KERNEL=$1
  local FSTYPE=$2
  local NAME=$3

  local ENTRY_NAME=$(getEntryName ${KERNEL} ${FSTYPE})

cat <<EOF

menuentry '${ENTRY_NAME}' --class gnu-linux --class gnu --class os {
  echo "Loading modules..."

  insmod xzio
  insmod part_msdos

  echo "Loading kernel \"${KERNEL}\"..."

  set root=${BOOT_PART}

  linux  /vmlinuz-${KERNEL} root=${ROOT_DEV} lvm_loops_host_dev=${HOST_DEV} lvm_loops_host_fstype=${FSTYPE} lvm_loops_host_fsoptions=${HOST_DEV_FSOPTIONS} lvm_loops_mask=${LVM_LOOPS_MASK} max_loop=${MAX_LOOPS} ${KERNEL_DEFAULTS}

  echo "Booting..."
  initrd /initrd.img-${KERNEL}
}
EOF

}

function getEntryName {
  local KERNEL=$1
  local FSTYPE=$2
  local NAME_EXT=$3

  echo "Buddy Linux${NAME_EXT} (${KERNEL}, ${FSTYPE})"
}

# Get kernels list

KERNELS=$(for file in /boot/vmlinuz-* /vmlinuz-* /boot/kernel-* ; do
  if grub_file_is_not_garbage "${file}" ; then echo -n "${file} " ; fi
done)

LATEST_KERNEL=$(version_find_latest ${KERNELS} | sed -e "s,^[^0-9]*-,,g")

# Adding entries

for kernel in ${KERNELS}; do
  KERNEL=$(basename $kernel | sed -e "s,^[^0-9]*-,,g")
  addMenuEntry ${KERNEL} ${HOST_DEV_FSTYPE}
  echo "Found Buddy Linux (${KERNEL}, ${HOST_DEV_FSTYPE})." 1>&2

  PARAGON_FS=ufsd
  PARAGON_DRIVER=/lib/modules/${KERNEL}/kernel/external/${PARAGON_FS}/${PARAGON_FS}.ko

  if [ -f "${PARAGON_DRIVER}" ]; then
    addMenuEntry ${KERNEL} ${PARAGON_FS} " / Paragon"
    echo "Found Buddy Linux / Paragon (${KERNEL}, ${PARAGON_FS})." 1>&2
  fi
done

# Set default

if [ -z "${GRUB_DEFAULT}" ]; then
  DEFAULT_ENTRY=$(getEntryName ${LATEST_KERNEL} ${HOST_DEV_FSTYPE})

  echo "default='${DEFAULT_ENTRY}'"
  echo "Default kernel entry set to '${DEFAULT_ENTRY}'." 1>&2
fi
