#!/bin/bash

function printError {
    echo -e "$@" >&2
}

function printInfo {
    echo -e "$@" >&1
}

function showHelp {
    printInfo "Synopsis:\n"
    printInfo "  $(basename $0) [OPTIONS]\n"
    printInfo "    -h | --help  this screen."
    printInfo "    -a | --all  : update all kernel (else: only current kernel)."
    printInfo ""
}

function parseOptions {
    GET_OPT=$(getopt -o -ha --long help,all -- "$@" 2>&1 1>/dev/null)
    EXIT_CODE=$?

    if [ ${EXIT_CODE} != 0 ]; then
        printError "Arguments parsing error(s):"
        printError "$(echo "${GET_OPT}" | sed -e 's/getopt: / - /')"
        exit $?
    fi

    while true; do
        case "$1" in
            -a | --all )
                PARAM_CURRENT_ONLY=0
                shift
            ;;

            -h | --help )
                showHelp
                exit 1
            ;;

            * )
            break
            ;;
        esac
    done
}

PARAM_CURRENT_ONLY=1
parseOptions $@

if [ ${PARAM_CURRENT_ONLY} -eq 1 ]; then

  CURRENT_KERNEL=$(uname -r)
  /usr/bin/dracut -f /boot/initrd.img-${CURRENT_KERNEL} ${CURRENT_KERNEL} || exit $?

else
  MODS_DIR=/lib/modules

  for MOD_DIR in $(ls -1 ${MODS_DIR}); do
    ( ls ${MODS_DIR}/${MOD_DIR}/modules.dep* 2>&1 1>/dev/null ) && \
    ( /usr/bin/dracut -f /boot/initrd.img-${MOD_DIR} ${MOD_DIR} || exit $? )
  done

fi
